### ISSUE TITLE
CREATE_FAILED during npx cdk deploy

### ISSUE THREAD

**Issue by GiuseppeSergi3** [aws-samples/prompt-engineering-with-anthropic-claude-v-3#2]
Hello everyone, after running the 'npx cdk deploy' command, I'm encountering the following errors that lead to deployment failure:
<img width="650" alt="image" src="https://github.com/aws-samples/prompt-engineering-with-anthropic-claude-v-3/assets/100352697/a5f7a459-6326-4259-8102-f0c42105aa97">

I'm trying to deploy the chatbot (via Cloud9 environment) in the Paris region.
Does anyone know how to resolve this?

Thank you,
Giuseppe

**Comment by jawhnycooke** [comment]
i think you may have the wrong repo. This repo is for prompt engineering and does not use cdk to deploy

**Comment by GiuseppeSergi3** [comment]
Yes, I mistakenly opened the issue in the wrong repository. I apologize for the inconvenience.
